/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './main-content-item.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators.js';

/**
 * Related documents.
 *
 * @element cds-main-content-item
 */

@customElement(`${prefix}-main-content-item`)
class CDSMainContentItem extends LitElement {
  @property({ type: String }) size = '05';
  render() {
    return html`
      <div class="size--${this.size}">
        <slot></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSMainContentItem;
