/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './doc-page-header.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-doc-page-header
 */

@customElement(`${prefix}-doc-page-header`)
class CDSDocPageHeader extends LitElement {
  @property({ type: String }) title = 'Darbība';
  /**
   * The type of the title. Possible values are `title` and `subtitle`.
   */
  @property({ type: String }) type = 'title';

  render() {
    return html`
      <div class="doc-page-header">
        <div class="doc-page-header__breadcrumb">
          <slot name="breadcrumb"></slot>
        </div>
        <div class="doc-page-header__content">
          <div
            class="doc-page-header__title doc-page-header__title--${this.type}">
            ${this.title}
          </div>
          <div class="doc-page-header__button">
            <slot name="button"></slot>
          </div>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDocPageHeader;
