/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './status-change-panel.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-status-change-panel
 */
@customElement(`${prefix}-status-change-panel`)
class CDSStatusChangePanel extends LitElement {
  @property({ type: String }) projectId = '1.1.1.1/16/A/004';
  @property({ type: Array }) statusItems = [
    { value: 'String', text: 'Status' },
  ];
  @property({ type: String }) selectedStatus = 'Status_1';
  itemSelectedHandler = (event) => {
    this.selectedStatus = event.detail.item.__value;
    //@ts-ignore
    this.shadowRoot.getElementById('status-change-modal').open = true;
  };

  render() {
    return html`
      <div class="container">
        <div>
          <cds-button size="md">Saglabāt</cds-button>
        </div>
        <div class="right-button">
          <div class="dropdown-container">
            <cds-dropdown
              class="cds-theme-zone-turn-dropdown-button"
              label="Mainīt statusu"
              @cds-dropdown-selected="${this.itemSelectedHandler}">
              ${this.statusItems?.map(
                (item) => html`
                  <cds-dropdown-item
                    class="cds-theme-zone-turn-dropdown-button-test"
                    value="${item?.value}"
                    >${item?.text}</cds-dropdown-item
                  >
                `
              )}
            </cds-dropdown>
          </div>
        </div>
      </div>

      <cds-modal id="status-change-modal">
        <cds-modal-header>
          <cds-modal-close-button></cds-modal-close-button>
          <cds-modal-label>Dokumenti</cds-modal-label>
          <cds-modal-heading>Dokumenta pievienošana</cds-modal-heading>
        </cds-modal-header>
        <cds-modal-body>
          <p>
            Spiežot “atgriezt nodaļas vadītājam” Jūs... paskaidrot, kādas sekas.
          </p>
          <cds-text-editor
            editorId="editor_status_modal_${this.selectedStatus}"
            editorConfig='{
          "editorTitle": "Pārskatīšanas / Apstrīdēšanas gaitas piezīmes"
          }'></cds-text-editor>
        </cds-modal-body>
        <cds-modal-footer>
          <cds-modal-footer-button kind="secondary" data-modal-close
            >Cancel</cds-modal-footer-button
          >
          <cds-modal-footer-button kind="primary">Save</cds-modal-footer-button>
        </cds-modal-footer>
      </cds-modal>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSStatusChangePanel;
