/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './subselection.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Subselection
 *
 * @element cds-subselection
 */
@customElement(`${prefix}-subselection`)
class CDSTurnSubselection extends FocusMixin(LitElement) {
  /**
   * if hide is true, the subselection will be hidden
   */
  @property({ type: Boolean }) hideSubselection = false;

  render() {
    return html`
      <div
        class="subselection ${this.hideSubselection
          ? 'subselection--hidden'
          : ''}">
        <slot></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnSubselection;
