/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './related-documents.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-related-documents
 */
@customElement(`${prefix}-related-documents`)
class CDSRelatedDocuments extends FocusMixin(LitElement) {
  @property({ type: String }) title = 'Saistītie dokumenti';

  render() {
    // const { _handleSlotChange: handleSlotChange } = this;
    return html`
      <div class="related-documents">
        <p class="related-documents__title">${this.title}</p>
        <ul class="related-documents__links">
          <slot></slot>
        </ul>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSRelatedDocuments;
