/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './contextual-header.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-contextual-header
 */

@customElement(`${prefix}-contextual-header`)
class CDSHeaderProjectBlock extends LitElement {
  @property({ type: String }) title = '';

  render() {
    return html`
      <div class="container">
        <cds-accordion
          alignment="start"
          class="cds--css-grid-column cds--col-span-100">
          <cds-accordion-item title="${this.title}">
            <slot></slot>
          </cds-accordion-item>
        </cds-accordion>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSHeaderProjectBlock;
