/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './diff-status.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

import { green, gray, purple } from '@carbon/colors';

import LowSeverityIcon from '@carbon/icons/lib/low-severity';
import CautionIcon from '@carbon/icons/lib/caution';
import CircleStrokeIcon from '@carbon/icons/lib/circle-stroke';
/**
 * Related documents.
 *
 * @element cds-diff-status
 */

@customElement(`${prefix}-diff-status`)
class CDSDiffStatus extends LitElement {
  @property({ type: Number }) diffStatusType = 0;
  @property({ type: String }) diffStatusText = '';
  @property({ type: String }) diffStatusDate = '';
  @property({ type: String }) diffStatusEditor = '';

  render() {
    return html`
      ${this.diffStatusType !== 0
        ? html`
            <div>
              ${this.diffStatusEditor.length > 0
                ? html`<cds-tooltip align="top">
                    <div class="sb-tooltip-trigger" aria-labelledby="content">
                      <div class="diff-status">
                        <div class="diff-status__box">
                          <div class="diff-status__icon">
                            ${this.renderIcon()}
                          </div>
                          <div class="diff-status__title">
                            ${this.diffStatusText}
                          </div>
                          <div class="diff-status__date">
                            ${this.diffStatusDate}
                          </div>
                        </div>
                      </div>
                    </div>
                    <cds-tooltip-content id="content">
                      ${this.diffStatusEditor}
                    </cds-tooltip-content>
                  </cds-tooltip>`
                : html` <div class="diff-status">
                    <div class="diff-status__box">
                      <div class="diff-status__icon">${this.renderIcon()}</div>
                      <div class="diff-status__title">
                        ${this.diffStatusText}
                      </div>
                      <div class="diff-status__date">
                        ${this.diffStatusDate}
                      </div>
                    </div>
                  </div>`}
            </div>
          `
        : ''}
    `;
  }

  renderIcon() {
    switch (this.diffStatusType) {
      case 0:
        break;
      case 1:
        return html`${CautionIcon({ fill: purple[60] })}`;
      case 2:
        return html`${CircleStrokeIcon({ fill: green[50] })}`;
      case 3:
        return html`${LowSeverityIcon({ fill: gray[60] })}`;
      case 4:
        return html`${LowSeverityIcon({ fill: gray[60] })}`;
      default:
        break;
    }
    return null;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDiffStatus;
