/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './diff-status.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

import { green, gray, purple } from '@carbon/colors';

import LowSeverityIcon from '@carbon/icons/lib/low-severity';
import CautionIcon from '@carbon/icons/lib/caution';
import CircleStrokeIcon from '@carbon/icons/lib/circle-stroke';
/**
 * Related documents.
 *
 * @element cds-diff-status
 */

@customElement(`${prefix}-diff-status`)
class CDSDiffStatus extends LitElement {
  @property({ type: String }) type = 'added';
  @property({ type: String }) date = '20.10.2022';

  render() {
    return html`
      <div class="diff-status">
        <div class="diff-status__box">
          <div class="diff-status__icon">${this.renderIcon()}</div>
          <div class="diff-status__title">${this.renderLabel()}</div>
          <div class="diff-status__date">${this.date}</div>
          <div class="diff-status__diff"></div>
        </div>
      </div>
    `;
  }

  renderIcon() {
    switch (this.type) {
      case 'added':
        return html`${CircleStrokeIcon({ fill: green[50] })}`;
      case 'deleted':
        return html`${LowSeverityIcon({ fill: gray[60] })}`;
      case 'edited':
        return html`${CautionIcon({ fill: purple[60] })}`;
      default:
        return html`${CircleStrokeIcon({ fill: green[50] })}`;
    }
  }

  renderLabel() {
    switch (this.type) {
      case 'added':
        return 'Pievienots';
      case 'deleted':
        return 'Dzēsts';
      case 'edited':
        return 'Labots';
      default:
        return 'Pievienots';
    }
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDiffStatus;
