/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html, nothing } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './countdown-timer.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Countdown Timer.
 *
 * @element cds-countdown-timer
 */

@customElement(`${prefix}-countdown-timer`)
class CDSCountdownTimer extends LitElement {
  @property({ type: Object }) countdownDate = {
    years: 0,
    days: 0,
    hours: 0,
    minutes: 0,
  };
  @property({ type: String }) deadline = '';

  /**
   * Language of the text inside can be lv and en
   */
  @property({ type: String }) language = 'lv';
  /**
   * Title for the countdown timer
   */
  @property({ type: String }) title = '';
  /**
   * Type of the countdown timer
   * default - shows the full countdown timer
   * simple - shows only the time left
   */
  @property({ type: String }) type = 'default';

  getDayLabel(count, language) {
    if (language === 'en') {
      return count === 1 ? 'day' : 'days';
    }
    if (language === 'lv') {
      return count === 1 ? 'diena' : 'dienas';
    }
    return '';
  }

  render() {
    const deadline = new Date(this.deadline);

    const formattedDate = `${deadline.toLocaleDateString('lv-LV', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
    })} ${deadline.toLocaleTimeString('lv-LV', {
      hour: '2-digit',
      minute: '2-digit',
    })}`;

    const currentDate = new Date();
    const isDeadlineOver = deadline.getTime() < currentDate.getTime();

    //@ts-ignore
    const timeDifference = deadline - currentDate;

    const years = Math.floor(timeDifference / (365.25 * 24 * 60 * 60 * 1000));
    const days = Math.floor(
      (timeDifference % (365.25 * 24 * 60 * 60 * 1000)) / (24 * 60 * 60 * 1000)
    );
    const hours = Math.floor(
      (timeDifference % (24 * 60 * 60 * 1000)) / (60 * 60 * 1000)
    );
    const minutes = Math.floor(
      (timeDifference % (60 * 60 * 1000)) / (60 * 1000)
    );

    this.countdownDate = { years, days, hours, minutes };

    return html`
      ${this.type === 'default'
        ? html`
            <div class="countdown-timer">
              <div class="countdown-timer__wrapper">
                <div class="countdown-timer__title">${this.title}</div>
                ${isDeadlineOver
            ? html`<div
                      class="countdown-timer__time-left countdown-timer__time-left--overdue">
                      0 ${this.language === 'en' ? 'days' : 'dienas'} 0:00
                    </div>`
            : html`<div class="countdown-timer__time-left">
            ${this.countdownDate.years > 0
                ? `${this.countdownDate.years} ${this.language === 'en'
                  ? `year${this.countdownDate.years !== 1 ? 's' : ''}`
                  : this.countdownDate.years === 1 ? 'gads' : 'gadi'}`
                : ''}
                      ${this.countdownDate.days !== 0
                ? `${this.countdownDate.days} ${this.getDayLabel(
                  this.countdownDate.days,
                  this.language
                )} ${this.countdownDate.hours}:${this.countdownDate.minutes
                }`
                : `${this.countdownDate.hours}:${this.countdownDate.minutes}`}
                    </div>`}
                <div class="countdown-timer__time-actual">${formattedDate}</div>
              </div>
            </div>
          `
        : nothing}
      ${this.type === 'simple'
        ? html`
            <div class="mini-timer">
              <div class="mini-timer__title">${this.title}</div>
              ${isDeadlineOver
            ? html`<div
                    class="mini-timer__time-left mini-timer__time-left--overdue">
                    0 ${this.language === 'en' ? 'days' : 'dienas'} 0:00
                  </div>`
            : html`<div class="mini-timer__time-left">
                    ${this.countdownDate.days !== 0
                ? `${this.countdownDate.days} ${this.getDayLabel(
                  this.countdownDate.days,
                  this.language
                )} ${this.countdownDate.hours}:${this.countdownDate.minutes
                }`
                : `${this.countdownDate.hours}:${this.countdownDate.minutes}`}
                  </div>`}
            </div>
          `
        : nothing}
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSCountdownTimer;
