/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './chosen-categories.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-chossen-categories
 */

@customElement(`${prefix}-chosen-categories`)
class CDSBackTo extends LitElement {
  @property({ type: Array }) chosenCategoriesData: any = [];

  render() {
    return html`
      <cds-tile class="container"
        >${this.chosenCategoriesData.map(
          (item) =>
            html`<div class="cds-label-value-container">
              <div class="cds-label-value">
                <cds-label-value label=${item.label}
                  >${item.value}</cds-label-value
                >
              </div>
            </div>`
        )}
      </cds-tile>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSBackTo;
