/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './document-with-status.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Circle16 from '@carbon/icons/lib/circle-fill';
import { green, gray, red, yellow } from '@carbon/colors';

/**
 * Related documents.
 *
 * @element cds-document-with-status
 */
@customElement(`${prefix}-document-with-status`)
class CDSDocumentsWithStatus extends FocusMixin(LitElement) {
  @property({ type: String }) title = 'Projekta satura izmaiņu salīdzināšana';
  /**
   * Can be one of: information, success, error or warning.
   */
  @property({ type: String }) status = 'information';
  @property({ type: String }) statusText = 'Izmaiņu nav';
  @property({ type: String }) linkUrl = 'https://google.com';
  @property({ type: String }) linkText = 'Apskatīt';
 
  render() {
    const{title, status, statusText, linkUrl, linkText} = this;
    let fillColor: string;
  
    // Set fill color based on status
    switch (status) {
      case 'success':
        fillColor = green[40];
        break;
      case 'information':
        fillColor = gray[40];
        break;
      case 'error':
        fillColor = red[50];
        break;
      case 'warning':
        fillColor = yellow[30];
        break;
      default:
        fillColor = gray[40];
    }

    return html`
      <div class="document-with-status">
        <div class="document-with-status__content">
          <p class="document-with-status__title">${title}</p>
          <div class="document-with-status__status">
            <span class="document-with-status__status-icon">${Circle16({fill: fillColor})}</span>
            <p class="document-with-status__status-text">${statusText}</p>
          </div>
        </div>
        <div class="document-with-status__link">
          <cds-link
            href="${linkUrl}"
            target="_blank">
            ${linkText}   
          </cds-link>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDocumentsWithStatus;
