/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './document-with-status.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Circle16 from '@carbon/icons/lib/circle-fill';
// import { unsafeHTML } from 'lit-html/directives/unsafe-html.js';
// import DOMPurify from 'dompurify';

/**
 * Related documents.
 *
 * @element cds-document-with-status
 */
@customElement(`${prefix}-document-with-status`)
class CDSDocumentsWithStatus extends FocusMixin(LitElement) {
  @property({ type: String }) title = 'Projekta satura izmaiņu salīdzināšana';
  @property({ type: Boolean }) status = false;
  @property({ type: String }) statusText = 'Izmaiņas ir veiktas';
  @property({ type: String }) linkUrl = 'https://google.com';
  @property({ type: String }) linkText = 'Apskatīt';
 
  render() {
    const{title, status, statusText, linkUrl, linkText} = this;
    return html`
      <div class="document-with-status">
        <div class="document-with-status__content">
          <p class="document-with-status__title">${title}</p>
          <div class="document-with-status__status">
            <span class="document-with-status__status-icon">${Circle16({fill: status? 'green' : 'grey'})}</span>
            <p class="document-with-status__status-text">${statusText}</p>
          </div>
        </div>
        <div class="document-with-status__link">
          <cds-link
            href="${linkUrl}">
            ${linkText}      
          </cds-link>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDocumentsWithStatus;
