/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './page-title.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * page title
 *
 * @element cds-page-title
 */

@customElement(`${prefix}-page-title`)
class CDSTurnPageTitle extends LitElement {
  @property({ type: String }) title = '';
  @property({ type: String }) subTitle = '';

  render() {
    return html`
      <div class="project-title">
        <h3 class="project-title__title">${this.title}</h3>
        ${this.subTitle
          ? html`<div class="project-title__subtitle">${this.subTitle}</div>`
          : ''}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnPageTitle;
