/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './main-content-block-open.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators.js';

/**
 * Related documents.
 *
 * @element cds-main-content-block-open
 */

@customElement(`${prefix}-main-content-block-open`)
class CDSMainContentBlock extends LitElement {
  @property({ type: Boolean }) withTabs = false;
  render() {
    return html`
      <link
        rel="stylesheet"
        href="https://demo.turn.lv/cfla_dist/assets/css/turn-carbon-grid.css" />
      <div class="container">
        <div class="green-block"></div>
        <div class="header-block cds--css-grid cds--css-grid--narrow">
          <slot name="header"></slot>
        </div>
        ${this.withTabs
          ? html`<div class="tabs-block">
              <slot name="tabs"></slot>
            </div>`
          : ''}
        ${!this.withTabs
          ? html`<div class="content-block cds--css-grid cds--css-grid--narrow">
              <slot name="content" class="content-block"></slot>
            </div>`
          : ''}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSMainContentBlock;
