/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './label-value.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
/**
 * Related documents.
 *
 * @element cds-label-value
 */

@customElement(`${prefix}-label-value`)
class CDSLabelValue extends LitElement {
  @property({ type: String }) label = 'Default label!';
  @property({ type: String }) value = '';
  @property({ type: String }) size = 'sm';

  render() {
    return html`
      <div class="container container--${this.size}">
        <div class="label">${this.label}</div>
        ${this.value.length > 0
          ? html`<div class="value">${unsafeHTML(this.value)}</div>`
          : html``}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSLabelValue;
