/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './version-history.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * version-history
 *
 * @element cds-version-history
 */

@customElement(`${prefix}-version-history`)
class CDSTurnVersionHistory extends FocusMixin(LitElement) {
  @property({ type: String }) version = '';
  @property({ type: String }) date = '';
  @property({ type: Array }) versionHistoryArray = [
    {
      versionLink: String,
      version: String,
      date: String,
      tagType: String,
      tagText: String,
    },
  ];

  versionHistoryModalOpen = () => {
    //@ts-ignore
    this.shadowRoot.getElementById('version-history-modal').open = true;
  };
  render() {
    return html` <div>
        v${this.version} Publicēšanas datums: no ${this.date}
        <span class="other-versions-link"
          ><cds-link @click=${this.versionHistoryModalOpen}
            >Apskatīt citas versijas</cds-link
          ></span
        >
      </div>

      <cds-modal id="version-history-modal">
        <cds-modal-header>
          <cds-modal-close-button></cds-modal-close-button>
          <cds-modal-label>Statusu vēsture</cds-modal-label>
          <cds-modal-heading>Statusa maiņas pamatojums</cds-modal-heading>
        </cds-modal-header>
        <cds-modal-body>
          <cds-table>
            <cds-table-head>
              <cds-table-header-row>
                <cds-table-header-cell>Versija</cds-table-header-cell>
                <cds-table-header-cell
                  >Publicesanas datus</cds-table-header-cell
                >
                <cds-table-header-cell>Statuss</cds-table-header-cell>
              </cds-table-header-row>
            </cds-table-head>
            <cds-table-body>
              ${this.versionHistoryArray.map((item) => {
                return html`<cds-table-row>
                  <cds-table-cell
                    ><cds-link
                      style="cursor: pointer"
                      href="${item.versionLink}"
                      >v${item.version}</cds-link
                    ></cds-table-cell
                  >
                  <cds-table-cell>${item.date}</cds-table-cell>
                  <cds-table-cell
                    ><cds-tag type="${item.tagType}"
                      >${item.tagText}</cds-tag
                    ></cds-table-cell
                  >
                </cds-table-row>`;
              })}
            </cds-table-body>
          </cds-table>
        </cds-modal-body>
      </cds-modal>`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnVersionHistory;
