/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './print-download.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

import Download16 from '@carbon/icons/lib/download/16';
import Printer16 from '@carbon/icons/lib/printer/16';

/**
 * print-download
 *
 * @element cds-print-download
 */
@customElement(`${prefix}-print-download`)
class CDSTurnPrintDownload extends FocusMixin(LitElement) {
  @property({ type: String }) downloadLink = '';
  @property({ type: String }) printLink = '';

  render() {
    return html`
      <div class="actions-container">
        ${this.downloadLink
          ? html`<a href="${this.downloadLink}" download>
              <cds-button
                size="sm"
                kind="ghost"
                class="download-icon"
                title="Download"
                >${Download16({ slot: 'icon', fill: '#027070' })}</cds-button
              >
            </a>`
          : ''}
        ${this.printLink
          ? html`<cds-button
              size="sm"
              kind="ghost"
              class="print-icon"
              title="Print"
              @click="${this.printPage}"
              >${Printer16({ slot: 'icon', fill: '#027070' })}</cds-button
            >`
          : ''}
      </div>
    `;
  }

  printPage() {
    window.print();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnPrintDownload;
