/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './header-title.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { unsafeHTML } from 'lit/directives/unsafe-html.js';

/**
 * Related documents.
 *
 * @element cds-header-title
 */

@customElement(`${prefix}-header-title`)
class CDSHeaderTitle extends LitElement {
  @property({ type: String }) title = '';
  @property({ type: String }) subTitle = '';
  @property({ type: Boolean }) leftNoGridSpacing = false;
  @property({ type: Boolean }) marginWrapper = false;

  render() {
    return html`
      <div
        class="header-title-container ${this.marginWrapper
          ? 'header-title-container--margin-wrapper'
          : ''} ${this.leftNoGridSpacing
          ? 'header-title-container--left-no-grid-spacing'
          : ''}">
        <h1 class="title">${this.title}</h1>
        ${this.subTitle.length > 0
          ? html`<h2 class="subtitle">${unsafeHTML(this.subTitle)}</h2>`
          : ''}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSHeaderTitle;
