/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './empty-state.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Divider
 *
 * @element cds-empty-state
 */
@customElement(`${prefix}-empty-state`)
class CDSTurnEmptyState extends FocusMixin(LitElement) {
  @property({ type: String }) text = '';
  @property({ type: String }) linkUrl = '';
  @property({ type: String }) linkText = '';

  /**
   * add attibute "disabled" if block should be disabled.
   */
  @property({ type: Boolean, reflect: true })
  disabled = false;

  protected _renderBlock() {
    const { text, linkUrl, linkText } = this;

    return html`
      <div class="empty-doc">
        <div class="empty-doc__text">${text}</div>
        <div class="empty-doc__link">
          <cds-link href="${linkUrl}"> ${linkText} </cds-link>
        </div>
      </div>
    `;
  }

  render() {
    const { disabled } = this;
    return disabled ? '' : this._renderBlock();
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnEmptyState;
