/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';

import styles from './table-expanded-row-wrapper.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Table expanded row wrapper.
 *
 * @element cds-table-expanded-row-wrapper
 */
@customElement(`${prefix}-table-expanded-row-wrapper`)
class CDSTurnTableExpandedRowWrapper extends LitElement {
  render() {
    return html`
      <div class="cds-turn-table-expanded-row-wrapper">
        <cds-divider size="5"></cds-divider>
        <slot></slot>
        <cds-divider size="5"></cds-divider>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnTableExpandedRowWrapper;
