/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../../../globals/settings';
import styles from './mani-projekti.scss';
import { carbonElement as customElement } from '../../../../globals/decorators/carbon-element';

@customElement(`${prefix}-mani-projekti`)
class CDSPMyProjectsView extends LitElement {
  render() {
    return html`
      <link
        rel="stylesheet"
        href="https://demo.turn.lv/cfla_dist/assets/css/turn-carbon-grid.css" />

      <cds-main-content-block storybook> hi </cds-main-content-block>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSPMyProjectsView;
