/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './divider.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';


/**
 * Divider
 *
 * @element cds-divider
 */
@customElement(`${prefix}-divider`)
class CDSTurnDivider extends FocusMixin(LitElement) {
  /**
   * Can be one of: 1-13. Sets margin-bottom using carbon $spacing.
   */
  @property({ type: Number }) size = 5;
 
  render() {
  
    return html`
      <hr class="divider divider--${this.size}"></hr>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnDivider;
