/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './page-empty-state.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Sprout32 from '@carbon/icons/lib/sprout/32';

/**
 * page-empty-state
 *
 * @element cds-page-empty-state
 */

@customElement(`${prefix}-page-empty-state`)
class CDSTurnPageTitle extends LitElement {
  @property({ type: String }) title = '';

  render() {
    return html` <div class="page-empty-state">
      <div class="page-empty-state__container">
        <div class="page-empty-state__icon">${Sprout32()}</div>
        <div class="page-empty-state__title">${this.title}</div>
        <div class="page-empty-state__text">
          <slot name="content"></slot>
        </div>
        <div class="page-empty-state__button">
          <slot name="button"></slot>
        </div>
        <div class="page-empty-state__link">
          <slot name="link"></slot>
        </div>
      </div>
    </div>`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnPageTitle;
