/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../../../globals/settings';
import styles from './ligums-grozijumi.scss';
import { carbonElement as customElement } from '../../../../globals/decorators/carbon-element';
import OverflowMenuVertical16 from '@carbon/icons/lib/overflow-menu--vertical/16';

@customElement(`${prefix}-ligums-grozijumi`)
class CDSPValuationList extends LitElement {
  render() {
    return html`
      <cds-page-title title="Līgums un grozījumi"></cds-page-title>
      <cds-table>
        <cds-table-head>
          <cds-table-header-row>
            <cds-table-header-cell>Projekta ID</cds-table-header-cell>
            <cds-table-header-cell>Projekta nosaukums</cds-table-header-cell>
            <cds-table-header-cell>Iestādes nosaukums</cds-table-header-cell>
            <cds-table-header-cell>Projekta st.</cds-table-header-cell>
            <cds-table-header-cell>Līguma stat.</cds-table-header-cell>
            <cds-table-header-cell></cds-table-header-cell>
          </cds-table-header-row>
        </cds-table-head>
        <cds-table-body>
          <cds-table-row>
            <cds-table-cell>1.1.1.1/16/A</cds-table-cell>
            <cds-table-cell
              >Neironu tīkli fleksīvo dabisko valodu apstrādei</cds-table-cell
            >
            <cds-table-cell>Latvijas Universitāte</cds-table-cell>
            <cds-table-cell>Sagatavošanā</cds-table-cell>
            <cds-table-cell>Neizveidots</cds-table-cell>
            <cds-table-cell>
              <cds-overflow-menu>
                ${OverflowMenuVertical16({
                  class: `${prefix}--overflow-menu__icon`,
                  slot: 'icon',
                })}
                <span slot="tooltip-content"> Options </span>
                <cds-overflow-menu-body>
                  <cds-overflow-menu-item>Izveidot</cds-overflow-menu-item>
                  <cds-overflow-menu-item>Atvērt</cds-overflow-menu-item>
                  <cds-overflow-menu-item divider danger
                    >Izdzēst</cds-overflow-menu-item
                  >
                </cds-overflow-menu-body>
              </cds-overflow-menu>
            </cds-table-cell>
          </cds-table-row>
        </cds-table-body>
      </cds-table>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSPValuationList;
