/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './diff-checker.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import * as Diff from './diff.min.js';

/**
 * Related documents.
 *
 * @element cds-diff-checker
 */

@customElement(`${prefix}-diff-checker`)
class CDSBackTo extends LitElement {
  @property({ type: String }) oldText = `asdashhdasdasxxx
  asdashhdasdasxxx
  asdashhdasdasxxx
  asdashhdasdasxxxasdashhdasdasxxx
  asdashhdasdasxxx
  asdashhdasdasxxxasdashhdasdasxxx
  vasdashhdasdasxxx
  asdasdasdasdasdasdas
  `;
  @property({ type: String }) newText = `asdashhdasdasxxx
  asdashhdasdasxxxasdasdasdsa
  asdashhdasdasxxxasdasd
  asdashhda
  vasdasdasd
  vadasdas
  asdashhdasdasxxxasdashhdaadasdassdaasdadsxxx
  
  asdasdasdasdaszxczxcz`;

  //@ts-ignore
  renderDiff(text, type) {
    const differences = Diff.diffChars(this.oldText, this.newText);
    return differences.map((part) => {
      const className =
        part.added && type === 'new'
          ? 'added'
          : part.removed && type === 'old'
          ? 'removed'
          : '';
      if (type === 'old' && !part.added) {
        return html`<span class=${className}>${part.value}</span>`;
      } else if (type === 'new' && !part.removed) {
        return html`<span class=${className}>${part.value}</span>`;
      }
    });
  }

  render() {
    return html`<div class="container">
      <div class="text-container">
        <h3>Old Text</h3>
        ${this.renderDiff(this.oldText, 'old')}
      </div>
      <div class="text-container">
        <h3>New Text</h3>
        ${this.renderDiff(this.newText, 'new')}
      </div>
    </div>`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSBackTo;
