/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './form-number.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
/**
 * Related documents.
 *
 * @element cds-form-number
 */

@customElement(`${prefix}-form-number`)
class CDSFormNumber extends LitElement {
  /**
   * Can be green red and blakc to set the border color.
   */
  @property({ type: String }) type = 'green';

  render() {
    const { type } = this;
    const typeClass = type ? `container__border-left-${type}` : '';

    return html`
      <div class="container ${typeClass}">
        <div class="top-line">
          <slot name="status" class="status"></slot>
          <slot name="overflow-menu" class="overflow-menu"></slot>
        </div>
        <cds-expandable-tile color-scheme="light" has-rounded-corners>
          <cds-tile-above-the-fold-content slot="above-the-fold-content">
            <slot name="above-the-fold-content"></slot>
          </cds-tile-above-the-fold-content>
          <cds-tile-below-the-fold-content>
            <cds-divider> </cds-divider>
            <slot name="below-the-fold-content"></slot>
          </cds-tile-below-the-fold-content>
        </cds-expandable-tile>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSFormNumber;
