/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './selection-card.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Calendar from '@carbon/icons/lib/calendar/16';

/**
 * Selection card.
 *
 * @element cds-selection-card
 */
@customElement(`${prefix}-selection-card`)
class CDSSelectionCard extends LitElement {
  @property({ type: String }) selectionUrl = '';
  @property({ type: String }) selectionTitle = '';
  @property({ type: String }) cardTitle = '';
  @property({ type: String }) projectDateTitle = '';
  @property({ type: String }) projectDateInfo = '';

  render() {
    const {
      selectionTitle,
      selectionUrl,
      cardTitle,
      projectDateInfo,
      projectDateTitle,
    } = this;

    return html`
      <div class="project-card-container">
        <div class="project-card-header">
          <div class="project-card-projects">
            <span class="project-header-id">Atlase ${selectionTitle}</span>
          </div>
          <slot name="overflow-menu"></slot>
        </div>
        <p class="project-card-desc">${cardTitle}</p>
        <div class="project-card-info">
          ${projectDateInfo
            ? html`
                <div class="project-card-info-section">
                  <div class="project-card-info-image">
                    ${Calendar({ slot: 'icon', fill: 'black' })}
                  </div>
                  <div class="project-card-info-item">
                    <p>${projectDateTitle}</p>
                    <h3>${projectDateInfo}</h3>
                  </div>
                </div>
              `
            : ''}
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSSelectionCard;
