/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './selection-card.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Calendar from '@carbon/icons/lib/calendar/16';
import Launch16 from '@carbon/icons/lib/launch/16';

/**
 * Selection card.
 *
 * @element cds-selection-card
 */
@customElement(`${prefix}-selection-card`)
class CDSSelectionCard extends LitElement {
  @property({ type: String }) SelectionNumber = '';
  @property({ type: String }) selectionUrl = '';
  @property({ type: String }) cardTitle = '';
  @property({ type: String }) cardTitleUrl = '';
  @property({ type: String }) projectDateTitle = '';
  @property({ type: String }) projectDateInfo = '';
  @property({ type: String }) buttonText = '';

  render() {
    const {
      SelectionNumber,
      selectionUrl,
      cardTitle,
      cardTitleUrl,
      projectDateInfo,
      projectDateTitle,
      buttonText,
    } = this;

    return html`
      <div class="selection-card">
        <div class="selection-card__header">
          <div class="selection-card__selections">
            <span class="selection-card__selections-title">Atlase </span>
            <cds-link href="${selectionUrl}">
              ${SelectionNumber} ${Launch16({ slot: 'icon' })}</cds-link
            >
          </div>
          <slot name="overflow-menu"></slot>
        </div>
        <a href="${cardTitleUrl}" class="selection-card__desc">${cardTitle}</a>
        <div class="selection-card__info">
          ${projectDateInfo
            ? html`
                <div class="selection-card__info-section">
                  <div class="selection-card__info-image">
                    ${Calendar({ slot: 'icon', fill: 'black' })}
                  </div>
                  <div class="selection-card__info-item">
                    <h3>${projectDateTitle}</h3>
                    <p>${projectDateInfo}</p>
                  </div>
                </div>
              `
            : ''}
        </div>
        <div class="selection-card__button">
          <cds-button size="sm" kind="secondary">${buttonText}</cds-button>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSSelectionCard;
