/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './added-file.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Document16 from '@carbon/icons/lib/document/16';

/**
 * Related documents.
 *
 * @element cds-added-file
 */

@customElement(`${prefix}-added-file`)
class CDSAddedFile extends LitElement {
  /**
   * The file name.
   */
  @property({ type: String }) fileName = '';
  @property({ type: String }) fileCreationDate = '';
  @property({ type: String }) fileCreatedPerson = '';
  @property({ type: String }) fileUrl = '';

  render() {
    return html`
      <div class="container">
        <div class="file-container">
          <span class="doc-icon"> ${Document16({ class: 'icon' })} </span>
          <cds-link
            class="file-name"
            href="${this.fileUrl}"
            download="${this.fileName}"
            >${this.fileName}</cds-link
          >
        </div>
        <div class="file-date">
          <span>${this.fileCreationDate}</span>
          <span>Pievienots fails</span> -
          <span>${this.fileCreatedPerson}</span>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSAddedFile;
