/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './status-control-panel.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-status-control-panel
 */
@customElement(`${prefix}-status-control-panel`)
class CDSStatusControlPanel extends LitElement {
  @property({ type: String }) projectId = '1.1.1.1/16/A/004';

  @property({ type: Array }) accordionItems = [
    { value: 'Status 1', text: 'Status 1' },
    { value: 'Status 2', text: 'Status 2' },
    { value: 'Status 3', text: 'Status 3' },
  ];
  @property({ type: Function }) dropdownHandler = () => {};

  render() {
    return html`
      <div class="container">
        <div>
          <cds-button size="md">Saglabāt</cds-button>
        </div>
        <div class="right-button">
          <cds-dropdown-button
            .accordionItems=${this.accordionItems}
            .dropdownHandler=${this.dropdownHandler}></cds-dropdown-button>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSStatusControlPanel;
