/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './project-card.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Calendar from '@carbon/icons/lib/calendar/16';
import ShoppingCart from '@carbon/icons/lib/shopping--cart/16';

/**
 * Related documents.
 *
 * @element cds-project-card
 */
@customElement(`${prefix}-project-card`)
class ProjectCard extends LitElement {
  @property({ type: String }) projectId = '';
  @property({ type: String }) tagTitle = '';
  @property({ type: String }) supervisorAuthority = '';
  @property({ type: String }) organization = '';
  @property({ type: String }) cardTitle = '';
  @property({ type: String }) cardTitleUrl = '';
  @property({ type: String }) tagType = '';
  @property({ type: String }) projectDateTitle = '';
  @property({ type: String }) projectDateInfo = '';
  @property({ type: String }) projectCostTitle = '';
  @property({ type: String }) projectCostInfo = '';

  render() {
    const {
      projectId,
      tagType,
      tagTitle,
      cardTitle,
      cardTitleUrl,
      projectDateInfo,
      projectCostInfo,
      projectCostTitle,
      projectDateTitle,
      supervisorAuthority,
      organization,
    } = this;

    return html`
      <div class="project-card-container">
        <div class="project-card-header">
          <div class="project-card-projects">
            <span class="project-header-id">Projekts - ${projectId}</span>
            <cds-tag
              type="${tagType}"
              title="${tagTitle}"
              class="project-header-tag">
              ${tagTitle}
            </cds-tag>
          </div>
          <slot name="overflow-menu" class="overflow-menu"></slot>
        </div>
        <div class="project-card-content">
          <a href="${cardTitleUrl}" class="project-card-desc">${cardTitle}</a>
          <div class="project-card-organization">${organization}</div>
        </div>
        <div class="project-card-info">
          ${projectDateInfo
            ? html`
                <div class="project-card-info-section">
                  <div class="project-card-info-image">
                    ${Calendar({ slot: 'icon', fill: 'black' })}
                  </div>
                  <div class="project-card-info-item">
                    <p>${projectDateTitle}</p>
                    <h3>${projectDateInfo}</h3>
                  </div>
                </div>
              `
            : ''}
          ${projectCostInfo
            ? html`
                <div class="project-card-info-section">
                  <div class="project-card-info-image">
                    ${ShoppingCart({ slot: 'icon', fill: 'black' })}
                  </div>
                  <div class="project-card-info-item">
                    <p>${projectCostTitle}</p>
                    <h3>${projectCostInfo}</h3>
                  </div>
                </div>
              `
            : ''}
        </div>
        ${supervisorAuthority
          ? html`
              <div class="project-card-authority">
                <span class="project-card-authority-title">Uzraugs:</span>
                <span class="project-card-authority-desc"
                  >${supervisorAuthority}</span
                >
              </div>
            `
          : ''}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default ProjectCard;
