/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './related-persons.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

import UserAvatar16 from '@carbon/icons/lib/user--avatar/16';
import UserAdmin16 from '@carbon/icons/lib/user--admin/16';

@customElement(`${prefix}-related-persons`)
class CDSRelatedPersons extends LitElement {
  @property() statusHistoryItems = [{}];
  @property() shortRole = 'PV';
  @property() personName = 'Inta Štāle';

  render() {
    return html`
      <div class="container">
        <span class="container__related-person">
          ${UserAvatar16({ slot: 'icon' })} ${this.shortRole}:
          ${this.personName}
        </span>
        <span class="container__related-person">
          ${UserAdmin16({ slot: 'icon' })} ${this.shortRole}: ${this.personName}
        </span>
        <span class="container__related-person">
          ${UserAvatar16({ slot: 'icon' })} ${this.shortRole}:
          ${this.personName}
        </span>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSRelatedPersons;
