/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './related-persons.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

import UserAvatar16 from '@carbon/icons/lib/user--avatar/16';
import UserAdmin16 from '@carbon/icons/lib/user--admin/16';
import UserProfile16 from '@carbon/icons/lib/user--profile/16';

/**
 * Related documents.
 *
 * @element cds-related-persons
 */

const iconMap = new Map([
  ['1', UserAvatar16],
  ['2', UserAdmin16],
  ['3', UserProfile16],
]);

@customElement(`${prefix}-related-persons`)
class CDSRelatedPersons extends LitElement {
  @property({ type: Array }) statusRelatedPersons: any = [];
  render() {
    return html`
      <div class="container">
        ${this.statusRelatedPersons.map(
          (person) => html`
            <span class="container__related-person">
              ${iconMap.get(person?.iconType)({ slot: 'icon' })}
              ${person?.shortRole}: ${person?.personName}
            </span>
          `
        )}
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSRelatedPersons;
