/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './project-card.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import Calendar from '@carbon/icons/lib/calendar/16';
import ShoppingCart from '@carbon/icons/lib/shopping--cart/16';

@customElement(`${prefix}-project-card`)
class ProjectCard extends LitElement {
  @property() projectId = '1.1.1.1/16/A/004';
  @property() tagTitle = 'Apstiprināts ar nosacījumu';
  @property() tagType = 'purple';
  @property() projectDateInfo = '05.01.2021 - 30.05.2028';
  @property() projectCostInfo = '500 345';

  render() {
    return html`
      <div class="project-card-container">
        <div class="project-card-header">
          <p class="project-header-id">Projekts - ${this.projectId}</p>
          <cds-tag
            type="${this.tagType}"
            title="${this.tagTitle}"
            class="project-header-tag">
            ${this.tagTitle}
          </cds-tag>
        </div>
        <p class="project-card-desc">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut
          condimentum diam id diam blandit congue.
        </p>
        <div class="project-card-info">
          <div class="project-card-info-section">
            <div class="project-card-info-image">
              ${Calendar({ slot: 'icon', fill: 'black' })}
            </div>
            <div class="project-card-info-item">
              <p>Projekta īstenošanas termiņš</p>
              <h3>${this.projectDateInfo}</h3>
            </div>
          </div>
          <div class="project-card-info-section">
            <div class="project-card-info-image">
              ${ShoppingCart({ slot: 'icon', fill: 'black' })}
            </div>
            <div class="project-card-info-item">
              <p>Projekta kopējas izmaksas EUR</p>
              <h3>${this.projectCostInfo}</h3>
            </div>
          </div>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default ProjectCard;
