/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './label-with-help.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Label with help
 *
 * @element cds-label-with-help
 */

@customElement(`${prefix}-label-with-help`)
class CDSLabelWithHelp extends LitElement {
  @property({ type: String }) label = '';
  @property({ type: String }) value = '';
  @property({ type: String }) size = '';

  render() {
    return html`
      <div class="label-with-help">
        <div class="label-with-help__label">${this.label}</div>
        <slot class="label-with-help__help"></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSLabelWithHelp;
