/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './main-content-block-v2.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators.js';

/**
 * Related documents.
 *
 * @element cds-main-content-block-v2
 */

@customElement(`${prefix}-main-content-block-v2`)
class CDSMainContentBlockv2 extends LitElement {
  @property({ type: Boolean }) withTabs = false;
  render() {
    return html`
      <link
        rel="stylesheet"
        href="https://demo.turn.lv/cfla_dist/assets/css/turn-carbon-grid.css" />
      <div class="container">
        <div class="green-block"></div>
        <div class="header-block cds--css-grid cds--css-grid--narrow">
          <slot name="header"></slot>
        </div>
        <div class="cds--css-grid cds--css-grid--narrow">
          <div class="cds--css-grid-column cds--col-span-100">
            <slot name="tabs"></slot>
          </div>
        </div>
        <div class="content-block cds--css-grid cds--css-grid--narrow">
          <div class="cds--css-grid-column cds--col-span-4">
            <slot name="sidenav"></slot>
          </div>
          <div class="cds--css-grid-column cds--col-span-5">
            <slot name="content"></slot>
          </div>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSMainContentBlockv2;
