/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './doc-page.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators.js';

/**
 * doc-page-sidenav
 *
 * @element cds-doc-page-sidenav
 */

@customElement(`${prefix}-doc-page-sidenav`)
class CDSDocPageSidenav extends LitElement {
  @property({ type: Boolean }) withTabs = false;
  render() {
    return html`
      <div class="container">
        <slot></slot>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDocPageSidenav;
