/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './doc-page.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators.js';

/**
 * doc-page-tab-content
 *
 * @element cds-doc-page-tab-content
 */

@customElement(`${prefix}-doc-page-tab-content`)
class CDSDocPageTabContent extends LitElement {
  // Property to accept the array of tabs
  @property({ type: Boolean }) withSidenav = false;
  @property({ type: Boolean }) withBreadcrumbs = false;
  @property({ type: Boolean }) withPrintDownload = false;

  render() {
    return html`
      <link
        rel="stylesheet"
        href="https://demo.turn.lv/cfla_dist/assets/css/turn-carbon-grid.css" />
      ${this.withSidenav
        ? html`
            <div class="doc-white-bgr cds--subgrid cds--subgrid--narrow">
              <div
                class="doc-sidenav cds--css-grid-column cds--sm:col-span-100 cds--md:col-span-4 cds--lg:col-span-4 cds--xlg:col-span-4 cds--max:col-span-4">
                <div class="doc-print-sidenav-block"></div>
                <div class="doc-print-sidenav-block-gray"></div>
                <div class="doc-white-bgr">
                  <slot name="tab-sidenav"></slot>
                </div>
              </div>
              <div
                class="doc-white-bgr cds--css-grid-column cds--sm:col-span-100 cds--md:col-span-4 cds--lg:col-span-12 cds--xlg:col-span-12 cds--max:col-span-12">
                <cds-divider size="3"></cds-divider>
                ${this.withPrintDownload
                  ? html` <slot name="tab-print-download"></slot>`
                  : html` <div class="doc-print-download-empty-block"></div>`}

                <slot name="tab-sidenav-mobile"></slot>
                ${this.withBreadcrumbs
                  ? html` <div class="doc-breadcrumbs">
                      <slot name="tab-breadcrumbs"></slot>
                    </div>`
                  : html` <div
                      class="doc-content-empty-breadcrumb-block"></div>`}
                <cds-divider size="8"></cds-divider>
                <slot name="tab-content"></slot>
                <cds-divider size="11"></cds-divider>
              </div>
            </div>
          `
        : html` <div class="cds--css-grid cds--css-grid--narrow">
            <div class="cds--css-grid-column cds--col-span-100">
              <cds-divider size="3"></cds-divider>
              ${this.withPrintDownload
                ? html` <slot name="tab-print-download"></slot>`
                : html` <div class="doc-print-download-empty-block"></div>`}
              ${this.withBreadcrumbs
                ? html` <div class="doc-breadcrumbs-full">
                    <slot name="tab-breadcrumbs"></slot>
                  </div>`
                : html``}
              <cds-divider size="6"></cds-divider>
              <slot name="tab-content"></slot>
              <cds-divider size="11"></cds-divider>
            </div>
          </div>`}
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSDocPageTabContent;
