/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './back-to.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import ArrowLeft from '@carbon/icons/lib/arrow--left/32';

/**
 * Related documents.
 *
 * @element cds-back-to
 */

@customElement(`${prefix}-back-to`)
class CDSBackTo extends LitElement {
  @property({ type: String }) title = 'Back to';
  @property({ type: String }) link = '#';

  render() {
    return html`
      <div class="container">
        <a href="${this.link}" class="link">
          ${ArrowLeft({ slot: 'icon', fill: 'black' })}
        </a>
        <p class="title">${this.title}</p>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSBackTo;
