/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './status-history.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

@customElement(`${prefix}-status-history`)
class CDSStatusHistory extends LitElement {
  @property() currenStatusColor = 'green';
  @property() currenStatusTitle = 'CFLA pārdomas';
  @property() currenStatusDate = '25.10.2019 10:34';
  @property() statusHistoryItems = [{}];
  render() {
    return html`
      <div class="container">
        <div class="container__current-status">
          <cds-tag
            type="${this.currenStatusColor}"
            title="${this.currenStatusTitle}"
            >${this.currenStatusTitle}
          </cds-tag>
          <span>${this.currenStatusDate}</span>
        </div>
        <div class="container__status-history">
          <cds-accordion alignment="start">
            <cds-accordion-item title="Statūsu vēsture">
              <p>
                25.10.2019 10:34 Atgriezta precizēšanai - Elīne Millere
                <cds-link>Pamatojums</cds-link>
              </p>
              <p>
                25.09.2019 16:13 Atgriezta precizēšanai - Elīne Millere
                <cds-link>Pamatojums</cds-link>
              </p>
            </cds-accordion-item>
          </cds-accordion>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSStatusHistory;
