/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './status-history.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-status-history
 */

@customElement(`${prefix}-status-history`)
class CDSStatusHistory extends LitElement {
  @property({ type: String }) currenStatusColor = 'green';
  @property({ type: String }) currenStatusTitle = 'CFLA pārdomas';
  @property({ type: String }) currenStatusDate = '25.10.2019 10:34';
  @property({ type: Array }) statusHistoryItems = [
    {
      date: '25.10.2019 10:34',
      status: 'Atgriezta precizēšanai 1',
      author: 'Elīne Millere',
      pamatojums: 'Pamatojums 1',
      id: '1',
    },
    {
      date: '25.09.2019 16:13',
      status: 'Atgriezta precizēšanai 2',
      author: 'Test author',
      pamatojums: 'Pamatojums 2',
      id: '2',
    },
  ];

  @property() modalContent = {
    date: '25.10.2019 10:34',
    status: 'Atgriezta precizēšanai',
    author: 'Elīne Millere',
    pamatojums: 'Pamatojums test',
    id: '1',
  };

  statusHistoryInfoModalOpen = (item) => {
    this.modalContent = item;
    //@ts-ignore
    this.shadowRoot.getElementById('status-history-info-modal').open = true;
  };

  render() {
    return html`
      <div class="container">
        <div class="container__current-status">
          <cds-tag
            type="${this.currenStatusColor}"
            title="${this.currenStatusTitle}"
            >${this.currenStatusTitle}
          </cds-tag>
          <p class="container__current-status--date">
            ${this.currenStatusDate}
          </p>
        </div>
        <div class="container__status-history">
          <cds-accordion alignment="start">
            <cds-accordion-item title="Statusu vēsture">
              ${this.statusHistoryItems.map(
                (item) => html`
                  <p id="${item.id}">
                    ${item.date} ${item.status}
                    ${item.author ? ' — ' + item.author : ''}
                    ${item.pamatojums && item.pamatojums.length > 0
                      ? html`
                          <cds-link
                            style="cursor: pointer;"
                            @click=${() =>
                              this.statusHistoryInfoModalOpen(item)}
                            >Pamatojums</cds-link
                          >
                        `
                      : ''}
                  </p>
                  <cds-divider size="2"></cds-divider>
                `
              )}
            </cds-accordion-item>
            <cds-divider size="2"></cds-divider>
          </cds-accordion>
        </div>
      </div>
      <cds-modal id="status-history-info-modal">
        <cds-modal-header>
          <cds-modal-close-button></cds-modal-close-button>
          <cds-modal-label>Statusu vēsture</cds-modal-label>
          <cds-modal-heading>Statusa maiņas pamatojums</cds-modal-heading>
        </cds-modal-header>
        <cds-modal-body>
          <cds-divider size="4"></cds-divider>
          <cds-label-value label="Statuss" value="${this.modalContent.status}">
          </cds-label-value>
          <cds-divider size="4"></cds-divider>
          <cds-label-value
            label="Statusa datums un laiks"
            value="${this.modalContent.date}">
          </cds-label-value
          ><cds-divider size="4"></cds-divider>
          <cds-label-value
            label="Statusa autors"
            value="${this.modalContent.author}">
          </cds-label-value
          ><cds-divider size="4"></cds-divider>
          <cds-label-value
            label="Pamatojums"
            value="${this.modalContent.pamatojums}">
          </cds-label-value
        ></cds-modal-body>
      </cds-modal>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSStatusHistory;
