/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './contextual-header-api.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Related documents.
 *
 * @element cds-contextual-header-api
 */

@customElement(`${prefix}-contextual-header-api`)
class CDSHeaderProjectBlock extends LitElement {
  @property({ type: Object }) contextualHeaderApiData: any = {};

  render() {
    return html`
      <div class="container">
        <cds-accordion
          alignment="start"
          class="cds--css-grid-column cds--col-span-100">
          <cds-accordion-item
            title="${this.contextualHeaderApiData.virsraksts}">
            ${this.contextualHeaderApiData.saturs.map(
              (item) =>
                (item.tips === 'link' &&
                  html` <cds-label-value-horizontal label="${item.nosaukums}">
                    <cds-link href="${item.links.saite}"
                      >${item.links.nosaukums}
                    </cds-link>
                  </cds-label-value-horizontal>`) ||
                (item.tips === 'status' &&
                  html` <cds-label-value-horizontal label="${item.nosaukums}">
                    <cds-tag type="${item.statuss.krasa}"
                      >${item.statuss.nosaukums}</cds-tag
                    >
                    ${item.statuss.datums
                      ? item.statuss.datums
                      : ''}</cds-label-value-horizontal
                  >`) ||
                (item.tips === 'divider' &&
                  html`<cds-divider size="3"></cds-divider>`) ||
                (item.tips === 'text' &&
                  html`<cds-label-value-horizontal label="${item.nosaukums}">
                    ${item.teksts
                      ? item.teksts
                      : ''}</cds-label-value-horizontal
                  >`)
            )}
          </cds-accordion-item>
        </cds-accordion>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSHeaderProjectBlock;
