/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import FocusMixin from '../../globals/mixins/focus';
import styles from './label-value-horizontal.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';


/**
 * Divider
 *
 * @element cds-label-value-horizontal
 */
@customElement(`${prefix}-label-value-horizontal`)
class CDSTurnLabelValueHorizontal extends FocusMixin(LitElement) {
  @property({ type: String }) label = "Atlases nosaukums";
 
  render() {
  
    return html`
      <div class="label-value-horizontal">
        <div class="label-value-horizontal__item">
          <div class="label-value-horizontal__label">
            ${this.label}: 
          </div>
          <div class="label-value-horizontal__slot">
            <slot></slot>
          </div>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSTurnLabelValueHorizontal;
