/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './page-title.scss';
import { property } from 'lit/decorators.js';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

@customElement(`${prefix}-page-title`)
class PageTitle extends LitElement {
  @property() title = 'Default page title';
  @property() link = '#';

  render() {
    return html`
      <div class="container">
        <h3 class="title">${this.title}</h3>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default PageTitle;
