/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './main-content-block.scss';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { property } from 'lit/decorators';

@customElement(`${prefix}-main-content-block`)
class CDSMainContentBlock extends LitElement {
  @property({ type: Boolean }) storybook = false;
  render() {
    return html`
      <link
        rel="stylesheet"
        href="https://demo.turn.lv/cfla_dist/assets/css/turn-carbon-grid.css" />
      <main class="${this.storybook === false ? 'page_main' : ''}">
        <div class="cds--css-grid  cds--css-grid--narrow">
          <slot></slot>
        </div>
      </main>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default CDSMainContentBlock;
